#pragma once

#include "ParamBank.hpp"
#include "dv_control_common/load_transfer.hpp"

#include <Eigen/Dense>

#include <algorithm>
#include <cmath>
#include <limits>
#include <stdexcept>
#include <string>

namespace skidpad_control
{

using skidpad_control::ParamBank;

// ============================================================================
//                              BASIC STRUCTS
// ============================================================================

struct WheelValues
{
    double FL = 0.0;
    double FR = 0.0;
    double RL = 0.0;
    double RR = 0.0;
};

enum class TorqueAllocationMode
{
    DV_QP,
    DV_AXLE,
    JACA
};

struct TorqueAllocationInput
{
    /*
        Suma momentów na wszystkich kołach.

        total_torque_cmd_Nm > 0  -> drive
        total_torque_cmd_Nm < 0  -> brake
    */
    double total_torque_cmd_Nm = 0.0;

    /*
        Target yaw moment generated by longitudinal wheel forces.

        In DV_QP:
            QP directly tries to achieve this Mz.

        In DV_AXLE/JACA:
            this value is interpreted directly as the yaw moment target
            for torque vectoring itself. We do not subtract base_yaw_moment_Nm.
    */
    double desired_yaw_moment_Nm = 0.0;

    /*
        Vehicle velocity in body frame.
    */
    double vx_mps = 0.0;
    double vy_mps = 0.0;
    double yaw_rate_radps = 0.0;

    /*
        Acceleration estimate for normal load estimation.

        ax > 0 -> acceleration, load goes rear
        ax < 0 -> braking, load goes front

        ay > 0 -> acceleration to the left, load goes right
    */
    double ax_mps2 = 0.0;
    double ay_mps2 = 0.0;

    /*
        Bicycle / rack steering angle [rad].

        The allocator receives only this single steering command.
        It converts it internally to real left/right front wheel angles
        using the fitted anti-Ackermann relation.
    */
    double delta_bicycle_rad = 0.0;

    /*
        Previous total torque actually published by allocator [Nm],
        wheel-side, signed.

        Used for normalized total-torque rate limiting.

        M_dot_up/down are dimensionless total-torque rates [1/s]:
            max_total_step = M_dot * model.drivetrain.max_motor_torque * dt

        Because the final allocator limiter uses one global scale for all
        wheels, the rate limit is computed on total torque, not per wheel.
    */
    double previous_total_limited_torque_Nm = 0.0;
    bool previous_total_limited_torque_valid = false;

    /*
        Safety / finished / hard stop paths may bypass the rate limiter and
        publish zero torque immediately.
    */
    bool bypass_torque_rate_limiter = false;
};

struct TorqueAllocationResult
{
    TorqueAllocationMode mode = TorqueAllocationMode::DV_QP;

    WheelValues Fz_N;

    /*
        Estymacja tylko do friction pre-limitera.
        To NIE jest pełny tire model.
    */
    WheelValues slip_angle_rad;
    WheelValues estimated_Fy_N;

    WheelValues torque_base_Nm;
    WheelValues torque_after_tv_Nm;
    WheelValues torque_limited_Nm;

    WheelValues max_abs_torque_from_friction_Nm;
    WheelValues max_abs_torque_after_all_limits_Nm;

    /*
        Final limiter debug.

        hard_limit_scale is always the actually applicable mechanical/friction
        scale in [0, 1]. It must never amplify torque.
    */
    double hard_limit_scale = 1.0;

    double input_total_torque_cmd_Nm = 0.0;
    double rate_limited_total_torque_cmd_Nm = 0.0;

    double previous_total_limited_torque_Nm = 0.0;
    double total_torque_rate_scale_min = 0.0;
    double total_torque_rate_scale_max = 1.0;
    double total_torque_rate_limited_scale = 1.0;

    double normalized_M_dot_up = 0.0;
    double normalized_M_dot_down = 0.0;
    double max_total_torque_step_up_Nm = 0.0;
    double max_total_torque_step_down_Nm = 0.0;

    bool torque_rate_limited = false;
    bool torque_rate_forced_over_hard_limit = false;
    bool torque_rate_limiter_bypassed = false;

    double global_scale = 1.0;
    bool limited = false;

    /*
        Final per-wheel engine-side limiter.

        This limiter is applied at the very end and uses one global scale for
        the whole wheel-torque vector, so it preserves the balance produced by
        base allocation + TV + previous limiters.

        Limits are configured on engine side per wheel:
            model.drivetrain.wheel_max_torque_engine_drive_Nm
            model.drivetrain.wheel_max_torque_engine_brake_Nm

        Converted to wheel side by gear_ratio.
    */
    double final_engine_per_wheel_limit_scale = 1.0;
    bool final_engine_per_wheel_limited = false;

    double wheel_drive_limit_from_engine_Nm = 0.0;
    double wheel_brake_limit_from_engine_Nm = 0.0;

    double vx_raw_mps = 0.0;
    double vx_for_slip_limiter_mps = 0.0;

    double requested_longitudinal_force_N = 0.0;
    double achieved_longitudinal_force_before_limit_N = 0.0;
    double achieved_longitudinal_force_after_limit_N = 0.0;
    double longitudinal_force_error_before_limit_N = 0.0;
    double longitudinal_force_error_after_limit_N = 0.0;

    double requested_yaw_moment_Nm = 0.0;
    double base_yaw_moment_Nm = 0.0;
    double tv_yaw_moment_target_Nm = 0.0;

    /*
        Real front wheel steering angles used internally by allocation,
        obtained from delta_bicycle_rad using anti-Ackermann fit.
    */
    double delta_left_rad = 0.0;
    double delta_right_rad = 0.0;

    double achieved_yaw_moment_before_limit_Nm = 0.0;
    double achieved_yaw_moment_after_limit_Nm = 0.0;
    double yaw_moment_error_before_limit_Nm = 0.0;
    double yaw_moment_error_after_limit_Nm = 0.0;

    double total_torque_after_tv_Nm = 0.0;
    double total_torque_limited_Nm = 0.0;

    /*
        DV_AXLE:
            tau = tau_base + [dTauF, -dTauF, dTauR, -dTauR]

        DV_QP:
            pola debugowe, liczone jako equivalent delta względem base.
    */
    double delta_front_tv_Nm = 0.0;
    double delta_rear_tv_Nm = 0.0;

    /*
        JACA:
            tau = tau_base + [dTauJ, -dTauJ, dTauJ, -dTauJ]
    */
    double delta_jaca_tv_Nm = 0.0;

    bool qp_solved = false;
    bool used_fallback = false;
};

// ============================================================================
//                              SMALL HELPERS
// ============================================================================

inline double clampLocal(
    const double x,
    const double lo,
    const double hi
)
{
    return std::max(lo, std::min(x, hi));
}

inline double safeAbs(
    const double x,
    const double eps = 1.0e-9
)
{
    return std::max(std::abs(x), eps);
}

inline const char* torqueAllocationModeToString(
    const TorqueAllocationMode mode
)
{
    switch (mode)
    {
        case TorqueAllocationMode::DV_QP:
            return "DV_QP";

        case TorqueAllocationMode::DV_AXLE:
            return "DV_AXLE";

        case TorqueAllocationMode::JACA:
            return "JACA";
    }

    return "UNKNOWN";
}

inline double speedForSlipAndLimiterMps(
    const double vx_mps
)
{
    constexpr double VX_MIN_FOR_SLIP_LIMITER_MPS =
        2.0;

    /*
        There is no reverse-driving mode here.

        This speed is used only for slip/Fy/friction-limiter estimation.
        Never preserve a negative vx sign.  Around standstill, vx can be
        slightly negative from noise even though the car is not reversing.
    */
    if (!std::isfinite(vx_mps))
    {
        return VX_MIN_FOR_SLIP_LIMITER_MPS;
    }

    return std::max(
        vx_mps,
        VX_MIN_FOR_SLIP_LIMITER_MPS
    );
}

inline bool paramFlag(
    const ParamBank& P,
    const std::string& key
)
{
    return P.get(key) > 0.5;
}

inline double getTrackWidthM(
    const ParamBank& P
)
{
    /*
        Common vehicle track width used by:
          - wheel-centre kinematics,
          - normal-load estimation,
          - yaw-moment calculation,
          - all torque-allocation modes.

        Keep the JACA-specific copy in JSON for compatibility with older code,
        but the allocator uses the common body geometry value.
    */
    return P.get("model.body.track_width");
}

inline double getTireRadiusM(
    const ParamBank& P
)
{
    return P.get("model.tire.R_tire");
}

inline double getGearRatio(
    const ParamBank& P
)
{
    return P.get("model.drivetrain.gear_ratio");
}

inline double getWheelDriveLimitFromEngineNm(
    const ParamBank& P
)
{
    const double limit_engine_Nm =
        P.get("model.drivetrain.wheel_max_torque_engine_drive_Nm");

    const double gear_ratio =
        getGearRatio(P);

    return
        std::max(0.0, limit_engine_Nm)
        * std::max(0.0, gear_ratio);
}

inline double getWheelBrakeLimitFromEngineNm(
    const ParamBank& P
)
{
    const double limit_engine_Nm =
        P.get("model.drivetrain.wheel_max_torque_engine_brake_Nm");

    const double gear_ratio =
        getGearRatio(P);

    return
        std::max(0.0, limit_engine_Nm)
        * std::max(0.0, gear_ratio);
}

inline double wheelTorqueToFxN(
    const ParamBank& P,
    const double torque_Nm
)
{
    return torque_Nm / safeAbs(getTireRadiusM(P));
}

inline double FxToWheelTorqueNm(
    const ParamBank& P,
    const double Fx_N
)
{
    return Fx_N * getTireRadiusM(P);
}

inline WheelValues scaleWheelValues(
    const WheelValues& in,
    const double scale
)
{
    WheelValues out;

    out.FL = in.FL * scale;
    out.FR = in.FR * scale;
    out.RL = in.RL * scale;
    out.RR = in.RR * scale;

    return out;
}

inline WheelValues minWheelValues(
    const WheelValues& a,
    const WheelValues& b
)
{
    WheelValues out;

    out.FL = std::min(a.FL, b.FL);
    out.FR = std::min(a.FR, b.FR);
    out.RL = std::min(a.RL, b.RL);
    out.RR = std::min(a.RR, b.RR);

    return out;
}

inline double sumWheelValues(
    const WheelValues& v
)
{
    return
        v.FL
        + v.FR
        + v.RL
        + v.RR;
}

inline double computeLongitudinalBodyForceFromWheelTorquesN(
    const ParamBank& P,
    const WheelValues& torque_Nm,
    const double delta_left_rad,
    const double delta_right_rad
)
{
    const double R_tire =
        getTireRadiusM(P);

    const double Fx_FL =
        torque_Nm.FL / safeAbs(R_tire);

    const double Fx_FR =
        torque_Nm.FR / safeAbs(R_tire);

    const double Fx_RL =
        torque_Nm.RL / safeAbs(R_tire);

    const double Fx_RR =
        torque_Nm.RR / safeAbs(R_tire);

    return
        Fx_FL * std::cos(delta_left_rad)
        + Fx_FR * std::cos(delta_right_rad)
        + Fx_RL
        + Fx_RR;
}

// ============================================================================
//                      ANTI-ACKERMANN STEERING FIT
// ============================================================================
//
// The allocator receives one bicycle/rack angle d.
// It converts d to real front-left and front-right wheel angles using the same
// fitted relation as the vehicle model:
//
//      delta_right = d + 0.09298947992255 * d^2 + 0.00324282679268
//      delta_left  = d - 0.09298947992255 * d^2 - 0.00324282679268
//
// Valid fitting range: about +/- 0.4528 rad.
// For max_steer = 0.38 rad this is inside the fitted range.
//
// ============================================================================

struct SteeringAngles
{
    double delta_left_rad = 0.0;
    double delta_right_rad = 0.0;
};

inline SteeringAngles computeAntiAckermannSteeringAngles(
    const double delta_bicycle_rad,
    const ParamBank& P
)
{
    (void)P;

    const double d =
        delta_bicycle_rad;

    constexpr double ACKERMANN_QUAD_COEFF =
        9.298947992255e-02;

    constexpr double TOE_OFFSET_RAD =
        3.242826792680e-03;

    const double d2 =
        d * d;

    SteeringAngles out;

    out.delta_left_rad =
        d
        - ACKERMANN_QUAD_COEFF * d2
        - TOE_OFFSET_RAD;

    out.delta_right_rad =
        d
        + ACKERMANN_QUAD_COEFF * d2
        + TOE_OFFSET_RAD;

    return out;
}

// ============================================================================
//                      SLIP ANGLE ESTIMATE LIKE TIRE MODEL
// ============================================================================
//
// Liczenie jak w tire modelu:
//
//      1. velocity at wheel center
//      2. rotate velocity into wheel frame
//      3. alpha = -atan2(vy_local, vx_local)
//
// Używa tylko:
//      model.body.l_f
//      model.body.l_r
//      model.body.track_width
//
// ============================================================================

inline double safeVxSignedForSlip(
    const double vx_mps
)
{
    constexpr double EPS_VX =
        1.0e-4;

    /*
        There is no reverse-driving mode in this controller.

        This helper is used only as atan2 denominator in the slip estimator.
        Therefore it must never return a negative value.  A tiny negative vx
        from odometry/encoder noise near standstill must not flip the slip
        angle by pi and saturate the friction ellipse.
    */
    if (!std::isfinite(vx_mps))
    {
        return EPS_VX;
    }

    return std::max(
        vx_mps,
        EPS_VX
    );
}

inline void rotateVelocityToWheelFrame(
    const double wheel_angle_rad,
    double& vx_mps,
    double& vy_mps
)
{
    const double c =
        std::cos(wheel_angle_rad);

    const double s =
        std::sin(wheel_angle_rad);

    const double vx0 =
        vx_mps;

    const double vy0 =
        vy_mps;

    /*
        Same transform as tire model:

            vx_local =  c * vx + s * vy
            vy_local = -s * vx + c * vy
    */

    vx_mps =
        c * vx0
        + s * vy0;

    vy_mps =
        -s * vx0
        + c * vy0;
}

inline WheelValues estimateWheelSlipAnglesLikeTireModelRad(
    const ParamBank& P,
    const double vx_mps,
    const double vy_mps,
    const double yaw_rate_radps,
    const double delta_left_rad,
    const double delta_right_rad
)
{
    const double l_f =
        P.get("model.body.l_f");

    const double l_r =
        P.get("model.body.l_r");

    const double half_track =
        0.5 * getTrackWidthM(P);

    /*
        Body frame:
            x forward
            y left

        Wheel positions:
            FL: x = +l_f, y = +track/2
            FR: x = +l_f, y = -track/2
            RL: x = -l_r, y = +track/2
            RR: x = -l_r, y = -track/2

        Velocity:
            vx_w = vx - yaw_rate * y_w
            vy_w = vy + yaw_rate * x_w
    */

    double vx_fl =
        vx_mps
        - yaw_rate_radps * half_track;

    double vy_fl =
        vy_mps
        + yaw_rate_radps * l_f;

    double vx_fr =
        vx_mps
        + yaw_rate_radps * half_track;

    double vy_fr =
        vy_mps
        + yaw_rate_radps * l_f;

    double vx_rl =
        vx_mps
        - yaw_rate_radps * half_track;

    double vy_rl =
        vy_mps
        - yaw_rate_radps * l_r;

    double vx_rr =
        vx_mps
        + yaw_rate_radps * half_track;

    double vy_rr =
        vy_mps
        - yaw_rate_radps * l_r;

    rotateVelocityToWheelFrame(
        delta_left_rad,
        vx_fl,
        vy_fl
    );

    rotateVelocityToWheelFrame(
        delta_right_rad,
        vx_fr,
        vy_fr
    );

    rotateVelocityToWheelFrame(
        0.0,
        vx_rl,
        vy_rl
    );

    rotateVelocityToWheelFrame(
        0.0,
        vx_rr,
        vy_rr
    );

    WheelValues alpha;

    alpha.FL =
        -std::atan2(
            vy_fl,
            safeVxSignedForSlip(vx_fl)
        );

    alpha.FR =
        -std::atan2(
            vy_fr,
            safeVxSignedForSlip(vx_fr)
        );

    alpha.RL =
        -std::atan2(
            vy_rl,
            safeVxSignedForSlip(vx_rl)
        );

    alpha.RR =
        -std::atan2(
            vy_rr,
            safeVxSignedForSlip(vx_rr)
        );

    constexpr double PI =
        3.14159265358979323846;

    const double alpha_min =
        -PI / 2.0 + 0.3;

    const double alpha_max =
        PI / 2.0 - 0.3;

    alpha.FL = clampLocal(alpha.FL, alpha_min, alpha_max);
    alpha.FR = clampLocal(alpha.FR, alpha_min, alpha_max);
    alpha.RL = clampLocal(alpha.RL, alpha_min, alpha_max);
    alpha.RR = clampLocal(alpha.RR, alpha_min, alpha_max);

    return alpha;
}

// ============================================================================
//                      NORMAL LOAD ESTIMATION FOR CONTROL
// ============================================================================
//
// Quasi-static wheel normal-load model consistent with dv_control.
//
// Required parameters:
//      model.body.m
//      model.body.g
//      model.body.l_f
//      model.body.l_r
//      model.body.h_cg
//      model.body.track_width
//      model.body.h1_roll
//      model.body.h2_roll
//      model.body.lambda_phi_elastic_lateral
//
// Roll convention:
//      h1_roll -> front roll-centre height [m]
//      h2_roll -> rear  roll-centre height [m]
//      lambda_phi_elastic_lateral -> front share of elastic roll moment [0, 1]
//
// ay > 0 means acceleration to the left, therefore load transfers to the
// right-hand wheels.
//
// The lateral transfer is split into:
//
//   1. geometric/direct component at each axle roll centre,
//   2. elastic component caused by the CG-to-roll-axis lever arm.
//
// With:
//      m_f = m*l_r/L
//      m_r = m*l_f/L
//
// the elastic roll-moment coefficient is:
//
//      H_el = m_f*(h_cg - h1_roll)
//           + m_r*(h_cg - h2_roll)
//
// The load transferred from the left wheel to the right wheel at each axle is:
//
//      dF_front = ay/track *
//          (m_f*h1_roll + lambda_phi*H_el)
//
//      dF_rear  = ay/track *
//          (m_r*h2_roll + (1-lambda_phi)*H_el)
//
// Wheel loads use +/- dF directly:
//
//      FL = Fz_front/2 - dF_front
//      FR = Fz_front/2 + dF_front
//      RL = Fz_rear /2 - dF_rear
//      RR = Fz_rear /2 + dF_rear
//
// This convention gives the correct total roll-moment equilibrium:
//
//      track*dF_front + track*dF_rear = m*ay*h_cg
//
// Optional aero load:
//      model.resistance.Cl1 * vx^2 -> front axle
//      model.resistance.Cl2 * vx^2 -> rear axle
// when model.resistance.use_aero == true.
//
// ============================================================================

inline WheelValues estimateWheelNormalLoadsN(
    const ParamBank& P,
    const double ax_relaxed_mps2,
    const double ay_relaxed_mps2,
    const double vx_mps = 0.0
)
{
    dv_control_common::WheelLoadModelParameters model;

    model.mass_kg = P.get("model.body.m");
    model.gravity_mps2 = P.get("model.body.g");
    model.lf_m = P.get("model.body.l_f");
    model.lr_m = P.get("model.body.l_r");
    model.h_cg_m = P.get("model.body.h_cg");
    model.track_front_m = getTrackWidthM(P);
    model.track_rear_m = getTrackWidthM(P);
    model.h_roll_center_front_m = P.get("model.body.h1_roll");
    model.h_roll_center_rear_m = P.get("model.body.h2_roll");
    model.lambda_elastic_front =
        P.get("model.body.lambda_phi_elastic_lateral");
    model.minimum_wheel_load_N =
        P.get("model.mass_transfer.minimum_wheel_load_N");

    double front_aero_N = 0.0;
    double rear_aero_N = 0.0;

    if (paramFlag(P, "model.resistance.use_aero"))
    {
        const double speed_mps =
            std::max(
                0.0,
                std::isfinite(vx_mps) ? vx_mps : 0.0
            );

        front_aero_N =
            P.get("model.resistance.Cl1") * speed_mps * speed_mps;

        rear_aero_N =
            P.get("model.resistance.Cl2") * speed_mps * speed_mps;
    }

    const dv_control_common::WheelLoadsN shared =
        dv_control_common::computeWheelLoadsN(
            model,
            ax_relaxed_mps2,
            ay_relaxed_mps2,
            front_aero_N,
            rear_aero_N
        );

    WheelValues out;
    out.FL = shared.FL;
    out.FR = shared.FR;
    out.RL = shared.RL;
    out.RR = shared.RR;
    return out;
}

// ============================================================================
//                      ESTIMATED FY FROM SLIP ANGLES
// ============================================================================
//
// Uproszczony lateral estimate do friction pre-limitera:
//
//      Fy = D * Fz * sin(C * atan(B * alpha))
//
// Parametry:
//      model.body.Bf
//      model.body.Cf
//      model.body.Df
//      model.body.Br
//      model.body.Cr
//      model.body.Dr
//
// ============================================================================

inline double estimateLateralForceFromSlipAngleN(
    const double alpha_rad,
    const double Fz_N,
    const double B,
    const double C,
    const double D
)
{
    return
        D
        * Fz_N
        * std::sin(
            C * std::atan(B * alpha_rad)
        );
}

inline WheelValues estimateWheelLateralForcesFromSlipAnglesN(
    const ParamBank& P,
    const WheelValues& slip_angle_rad,
    const WheelValues& Fz_N
)
{
    const double Bf =
        P.get("model.body.Bf");

    const double Cf =
        P.get("model.body.Cf");

    const double Df =
        P.get("model.body.Df");

    const double Br =
        P.get("model.body.Br");

    const double Cr =
        P.get("model.body.Cr");

    const double Dr =
        P.get("model.body.Dr");

    WheelValues Fy;

    Fy.FL =
        estimateLateralForceFromSlipAngleN(
            slip_angle_rad.FL,
            Fz_N.FL,
            Bf,
            Cf,
            Df
        );

    Fy.FR =
        estimateLateralForceFromSlipAngleN(
            slip_angle_rad.FR,
            Fz_N.FR,
            Bf,
            Cf,
            Df
        );

    Fy.RL =
        estimateLateralForceFromSlipAngleN(
            slip_angle_rad.RL,
            Fz_N.RL,
            Br,
            Cr,
            Dr
        );

    Fy.RR =
        estimateLateralForceFromSlipAngleN(
            slip_angle_rad.RR,
            Fz_N.RR,
            Br,
            Cr,
            Dr
        );

    return Fy;
}

// ============================================================================
//                          TORQUE ALLOCATION MODE
// ============================================================================

inline TorqueAllocationMode selectTorqueAllocationMode(
    const ParamBank& P
)
{
    const bool assume_dv_qp =
        paramFlag(
            P,
            "general.assume_dv_qp_torque_allocation"
        );

    const bool assume_dv_axle =
        paramFlag(
            P,
            "general.assume_dv_axle_torque_allocation"
        );

    const bool assume_jaca =
        paramFlag(
            P,
            "general.assume_jaca_torque_allocation"
        );

    const int selected_count =
        static_cast<int>(assume_dv_qp)
        + static_cast<int>(assume_dv_axle)
        + static_cast<int>(assume_jaca);

    if (selected_count != 1)
    {
        throw std::runtime_error(
            "Exactly one torque allocation mode must be enabled: "
            "general.assume_dv_qp_torque_allocation, "
            "general.assume_dv_axle_torque_allocation, "
            "general.assume_jaca_torque_allocation"
        );
    }

    if (assume_dv_qp)
    {
        return TorqueAllocationMode::DV_QP;
    }

    if (assume_dv_axle)
    {
        return TorqueAllocationMode::DV_AXLE;
    }

    return TorqueAllocationMode::JACA;
}

// ============================================================================
//                          BASE TORQUE ALLOCATION
// ============================================================================

inline WheelValues allocateBaseTorqueJacaNm(
    const ParamBank& P,
    const double total_torque_Nm
)
{
    const bool is_drive =
        total_torque_Nm >= 0.0;

    const double front_fraction_raw =
        is_drive
        ? P.get("general.jaca_front_torque_fraction_drive")
        : P.get("general.jaca_front_torque_fraction_brake");

    const double front_fraction =
        clampLocal(
            front_fraction_raw,
            0.0,
            1.0
        );

    const double rear_fraction =
        1.0 - front_fraction;

    WheelValues torque;

    torque.FL =
        0.5 * front_fraction * total_torque_Nm;

    torque.FR =
        0.5 * front_fraction * total_torque_Nm;

    torque.RL =
        0.5 * rear_fraction * total_torque_Nm;

    torque.RR =
        0.5 * rear_fraction * total_torque_Nm;

    return torque;
}

inline WheelValues allocateBaseTorqueDvAxleNm(
    const double total_torque_Nm,
    const WheelValues& Fz_N
)
{
    /*
        DV axle allocation:

        1. left side gets 50% total torque.
        2. right side gets 50% total torque.
        3. inside each side, front/rear split is proportional to Fz.

        This keeps base allocation neutral in left/right.
    */

    const double left_total_Nm =
        0.5 * total_torque_Nm;

    const double right_total_Nm =
        0.5 * total_torque_Nm;

    const double left_Fz_sum =
        std::max(
            1.0,
            Fz_N.FL + Fz_N.RL
        );

    const double right_Fz_sum =
        std::max(
            1.0,
            Fz_N.FR + Fz_N.RR
        );

    WheelValues torque;

    torque.FL =
        left_total_Nm
        * Fz_N.FL / left_Fz_sum;

    torque.RL =
        left_total_Nm
        * Fz_N.RL / left_Fz_sum;

    torque.FR =
        right_total_Nm
        * Fz_N.FR / right_Fz_sum;

    torque.RR =
        right_total_Nm
        * Fz_N.RR / right_Fz_sum;

    return torque;
}

// ============================================================================
//                      YAW MOMENT FROM WHEEL TORQUES
// ============================================================================
//
// Wheel force variable:
//      Fx_i = torque_i / R_tire
//
// Front wheels are steered:
//
//      Fx_body = Fx_wheel * cos(delta)
//      Fy_body = Fx_wheel * sin(delta)
//
// Moment:
//
//      Mz = x * Fy - y * Fx
//
// ============================================================================

inline double computeYawMomentFromWheelTorquesNm(
    const ParamBank& P,
    const WheelValues& torque_Nm,
    const double delta_left_rad,
    const double delta_right_rad
)
{
    const double l_f =
        P.get("model.body.l_f");

    const double half_track =
        0.5 * getTrackWidthM(P);

    const double R_tire =
        getTireRadiusM(P);

    const double Fx_FL =
        torque_Nm.FL / safeAbs(R_tire);

    const double Fx_FR =
        torque_Nm.FR / safeAbs(R_tire);

    const double Fx_RL =
        torque_Nm.RL / safeAbs(R_tire);

    const double Fx_RR =
        torque_Nm.RR / safeAbs(R_tire);

    const double Fx_FL_body =
        Fx_FL * std::cos(delta_left_rad);

    const double Fy_FL_body =
        Fx_FL * std::sin(delta_left_rad);

    const double Fx_FR_body =
        Fx_FR * std::cos(delta_right_rad);

    const double Fy_FR_body =
        Fx_FR * std::sin(delta_right_rad);

    const double Mz_FL =
        l_f * Fy_FL_body
        - half_track * Fx_FL_body;

    const double Mz_FR =
        l_f * Fy_FR_body
        + half_track * Fx_FR_body;

    const double Mz_RL =
        -half_track * Fx_RL;

    const double Mz_RR =
        half_track * Fx_RR;

    return
        Mz_FL
        + Mz_FR
        + Mz_RL
        + Mz_RR;
}

// ============================================================================
//                          DV AXLE TV
// ============================================================================

inline WheelValues applyDvAxleTorqueVectoringNm(
    const WheelValues& base_torque_Nm,
    const double delta_front_tv_Nm,
    const double delta_rear_tv_Nm
)
{
    WheelValues out =
        base_torque_Nm;

    /*
        DV axle:
            tau = tau_base + [dTauF, -dTauF, dTauR, -dTauR]
    */

    out.FL += delta_front_tv_Nm;
    out.FR -= delta_front_tv_Nm;

    out.RL += delta_rear_tv_Nm;
    out.RR -= delta_rear_tv_Nm;

    return out;
}

inline void computeDvAxleTorqueVectoringDeltasForYawMoment(
    const ParamBank& P,
    const WheelValues& Fz_N,
    const double tv_yaw_moment_target_Nm,
    const double delta_left_rad,
    const double delta_right_rad,
    double& delta_front_tv_Nm,
    double& delta_rear_tv_Nm
)
{
    const double R_tire =
        getTireRadiusM(P);

    const double l_f =
        P.get("model.body.l_f");

    const double track =
        getTrackWidthM(P);

    const double half_track =
        0.5 * track;

    /*
        Influence of [dTauF, -dTauF] on yaw moment.
    */

    const double coeff_front =
        (
            l_f * (
                std::sin(delta_left_rad)
                - std::sin(delta_right_rad)
            )
            - half_track * (
                std::cos(delta_left_rad)
                + std::cos(delta_right_rad)
            )
        )
        / safeAbs(R_tire);

    /*
        Influence of [dTauR, -dTauR] on yaw moment.
    */

    const double coeff_rear =
        -track / safeAbs(R_tire);

    const double Fz_front =
        Fz_N.FL + Fz_N.FR;

    const double Fz_rear =
        Fz_N.RL + Fz_N.RR;

    const double Fz_total =
        std::max(
            1.0,
            Fz_front + Fz_rear
        );

    const double front_tv_share =
        Fz_front / Fz_total;

    const double rear_tv_share =
        Fz_rear / Fz_total;

    const double yaw_moment_per_lambda =
        coeff_front * front_tv_share
        + coeff_rear * rear_tv_share;

    if (std::abs(yaw_moment_per_lambda) < 1.0e-9)
    {
        delta_front_tv_Nm = 0.0;
        delta_rear_tv_Nm = 0.0;
        return;
    }

    const double lambda =
        tv_yaw_moment_target_Nm / yaw_moment_per_lambda;

    delta_front_tv_Nm =
        lambda * front_tv_share;

    delta_rear_tv_Nm =
        lambda * rear_tv_share;
}

// ============================================================================
//                          JACA TV
// ============================================================================

inline WheelValues applyJacaTorqueVectoringNm(
    const WheelValues& base_torque_Nm,
    const double delta_jaca_tv_Nm
)
{
    WheelValues out =
        base_torque_Nm;

    /*
        JACA:
            tau = tau_base + [dTauJ, -dTauJ, dTauJ, -dTauJ]

        No additional front/rear balance inside TV.
        Front/rear balance is only in base allocation.
    */

    out.FL += delta_jaca_tv_Nm;
    out.FR -= delta_jaca_tv_Nm;

    out.RL += delta_jaca_tv_Nm;
    out.RR -= delta_jaca_tv_Nm;

    return out;
}

inline double computeJacaTorqueVectoringDeltaForYawMoment(
    const ParamBank& P,
    const double tv_yaw_moment_target_Nm,
    const double delta_left_rad,
    const double delta_right_rad
)
{
    const double R_tire =
        getTireRadiusM(P);

    const double l_f =
        P.get("model.body.l_f");

    const double track =
        getTrackWidthM(P);

    const double half_track =
        0.5 * track;

    const double coeff_front =
        (
            l_f * (
                std::sin(delta_left_rad)
                - std::sin(delta_right_rad)
            )
            - half_track * (
                std::cos(delta_left_rad)
                + std::cos(delta_right_rad)
            )
        )
        / safeAbs(R_tire);

    const double coeff_rear =
        -track / safeAbs(R_tire);

    const double coeff_jaca =
        coeff_front
        + coeff_rear;

    if (std::abs(coeff_jaca) < 1.0e-9)
    {
        return 0.0;
    }

    return
        tv_yaw_moment_target_Nm / coeff_jaca;
}

// ============================================================================
//                          DV QP ALLOCATION
// ============================================================================
//
// u = [Fx_FL, Fx_FR, Fx_RL, Fx_RR]^T
//
// G*u = [Fx_body_total, Mz_total]^T
//
// Corrected G:
//
// Fx row:
//      FL: cos(delta_left)
//      FR: cos(delta_right)
//      RL: 1
//      RR: 1
//
// Mz row:
//      FL: l_f*sin(delta_left)  - track/2*cos(delta_left)
//      FR: l_f*sin(delta_right) + track/2*cos(delta_right)
//      RL: -track/2
//      RR: +track/2
//
// Cost:
//
//      J = (G*u - target)^T Q (G*u - target) + u^T R u
//
// R penalizes low-Fz wheels more:
//
//      r_i = lambda * Fz_total/Fz_i * qFx
//
// Parametry wymagane:
//      general.torque_allocation_lambda_factor
//      general.torque_allocation_fx_ref
//      general.torque_allocation_mz_ref
//
// ============================================================================

inline bool solveDvQpWheelForcesN(
    const ParamBank& P,
    const WheelValues& Fz_N,
    const double fx_target_N,
    const double mz_target_Nm,
    const double delta_left_rad,
    const double delta_right_rad,
    WheelValues& wheel_forces_N
)
{
    const double l_f =
        P.get("model.body.l_f");

    const double track =
        getTrackWidthM(P);

    const double half_track =
        0.5 * track;

    const double Fx_ref =
        P.get("general.torque_allocation_fx_ref");

    const double Mz_ref =
        P.get("general.torque_allocation_mz_ref");

    const double lambda =
        P.get("general.torque_allocation_lambda_factor");

    const double qFx =
        1.0 / (safeAbs(Fx_ref) * safeAbs(Fx_ref));

    const double qMz =
        1.0 / (safeAbs(Mz_ref) * safeAbs(Mz_ref));

    Eigen::Matrix<double, 2, 4> G;

    G <<
        std::cos(delta_left_rad),
        std::cos(delta_right_rad),
        1.0,
        1.0,

        l_f * std::sin(delta_left_rad) - half_track * std::cos(delta_left_rad),
        l_f * std::sin(delta_right_rad) + half_track * std::cos(delta_right_rad),
        -half_track,
        +half_track;

    Eigen::Matrix2d Q =
        Eigen::Matrix2d::Zero();

    Q(0, 0) =
        qFx;

    Q(1, 1) =
        qMz;

    const double Fz_total =
        std::max(
            1.0,
            Fz_N.FL
            + Fz_N.FR
            + Fz_N.RL
            + Fz_N.RR
        );

    Eigen::Matrix4d R =
        Eigen::Matrix4d::Zero();

    R(0, 0) =
        lambda
        * Fz_total / std::max(1.0, Fz_N.FL)
        * qFx;

    R(1, 1) =
        lambda
        * Fz_total / std::max(1.0, Fz_N.FR)
        * qFx;

    R(2, 2) =
        lambda
        * Fz_total / std::max(1.0, Fz_N.RL)
        * qFx;

    R(3, 3) =
        lambda
        * Fz_total / std::max(1.0, Fz_N.RR)
        * qFx;

    Eigen::Vector2d target;

    target <<
        fx_target_N,
        mz_target_Nm;

    const Eigen::Matrix4d A =
        G.transpose() * Q * G
        + R;

    const Eigen::Vector4d c =
        G.transpose() * Q * target;

    Eigen::LLT<Eigen::Matrix4d> llt(A);

    if (llt.info() != Eigen::Success)
    {
        return false;
    }

    const Eigen::Vector4d u =
        llt.solve(c);

    if (llt.info() != Eigen::Success || !u.allFinite())
    {
        return false;
    }

    wheel_forces_N.FL = u(0);
    wheel_forces_N.FR = u(1);
    wheel_forces_N.RL = u(2);
    wheel_forces_N.RR = u(3);

    return true;
}

inline WheelValues wheelForcesToTorquesNm(
    const ParamBank& P,
    const WheelValues& wheel_forces_N
)
{
    WheelValues torque;

    torque.FL =
        FxToWheelTorqueNm(
            P,
            wheel_forces_N.FL
        );

    torque.FR =
        FxToWheelTorqueNm(
            P,
            wheel_forces_N.FR
        );

    torque.RL =
        FxToWheelTorqueNm(
            P,
            wheel_forces_N.RL
        );

    torque.RR =
        FxToWheelTorqueNm(
            P,
            wheel_forces_N.RR
        );

    return torque;
}

inline void computeEquivalentTvDeltasForDebug(
    const WheelValues& base_torque_Nm,
    const WheelValues& after_tv_torque_Nm,
    double& delta_front_tv_Nm,
    double& delta_rear_tv_Nm
)
{
    delta_front_tv_Nm =
        0.5
        * (
            (after_tv_torque_Nm.FL - base_torque_Nm.FL)
            - (after_tv_torque_Nm.FR - base_torque_Nm.FR)
        );

    delta_rear_tv_Nm =
        0.5
        * (
            (after_tv_torque_Nm.RL - base_torque_Nm.RL)
            - (after_tv_torque_Nm.RR - base_torque_Nm.RR)
        );
}

// ============================================================================
//                          FRICTION PRE-LIMITER
// ============================================================================
//
// Elipsa:
//
//      (Fx / (mu_x * Fz))^2 + (Fy / (mu_y * Fz))^2 <= 1
//
// Parametry wymagane:
//      general.use_friction_elipse_limiter
//      general.mu_x_friction_limit
//      general.mu_y_friction_limit
//      model.drivetrain.max_motor_torque
//          total wheel-side torque of the vehicle [Nm]
//
// Limiter końcowy:
//      jeden global scale dla całego wektora torque [Nm].
//
// Dzięki temu nie rozwalamy proporcji TV.
// ============================================================================

inline double computeMaxAbsFxFromFrictionEllipseN(
    const ParamBank& P,
    const double Fz_N,
    const double Fy_N
)
{
    const double mu_x =
        P.get("general.mu_x_friction_limit");

    const double mu_y =
        P.get("general.mu_y_friction_limit");

    const double Fz_safe =
        std::max(
            1.0,
            Fz_N
        );

    const double Fy_limit =
        std::max(
            1.0e-6,
            mu_y * Fz_safe
        );

    const double lateral_usage =
        std::abs(Fy_N) / Fy_limit;

    const double remaining =
        std::max(
            0.0,
            1.0 - lateral_usage * lateral_usage
        );

    return
        mu_x
        * Fz_safe
        * std::sqrt(remaining);
}

inline WheelValues computeMaxAbsWheelTorqueFromFrictionEllipseNm(
    const ParamBank& P,
    const WheelValues& Fz_N,
    const WheelValues& Fy_N
)
{
    WheelValues max_torque;

    max_torque.FL =
        FxToWheelTorqueNm(
            P,
            computeMaxAbsFxFromFrictionEllipseN(
                P,
                Fz_N.FL,
                Fy_N.FL
            )
        );

    max_torque.FR =
        FxToWheelTorqueNm(
            P,
            computeMaxAbsFxFromFrictionEllipseN(
                P,
                Fz_N.FR,
                Fy_N.FR
            )
        );

    max_torque.RL =
        FxToWheelTorqueNm(
            P,
            computeMaxAbsFxFromFrictionEllipseN(
                P,
                Fz_N.RL,
                Fy_N.RL
            )
        );

    max_torque.RR =
        FxToWheelTorqueNm(
            P,
            computeMaxAbsFxFromFrictionEllipseN(
                P,
                Fz_N.RR,
                Fy_N.RR
            )
        );

    return max_torque;
}

inline double getMaxTotalWheelTorqueNm(
    const ParamBank& P
)
{
    /*
        Nm-only convention. model.drivetrain.max_motor_torque is the maximum
        total wheel-side torque of the vehicle, so the mechanical per-wheel
        limit is one quarter of this value.
    */
    const double max_total_torque_Nm =
        P.get("model.drivetrain.max_motor_torque");

    if (!std::isfinite(max_total_torque_Nm) ||
        max_total_torque_Nm < 0.0)
    {
        throw std::runtime_error(
            "model.drivetrain.max_motor_torque must be finite and >= 0 "
            "and is interpreted as total wheel-side torque [Nm]"
        );
    }

    return max_total_torque_Nm;
}


inline double getMaxAbsWheelTorqueMechanicalPerWheelNm(
    const ParamBank& P
)
{
    return
        0.25
        * getMaxTotalWheelTorqueNm(P);
}


inline WheelValues getMaxAbsWheelTorqueMechanicalNm(
    const ParamBank& P
)
{
    const double max_torque_per_wheel_Nm =
        getMaxAbsWheelTorqueMechanicalPerWheelNm(P);

    WheelValues out;

    out.FL = max_torque_per_wheel_Nm;
    out.FR = max_torque_per_wheel_Nm;
    out.RL = max_torque_per_wheel_Nm;
    out.RR = max_torque_per_wheel_Nm;

    return out;
}

inline double getControlDtForTorqueAllocator(
    const ParamBank& P
)
{
    const double hz =
        P.get("model.frequency.steer_cmd_loop_hz");

    if (!std::isfinite(hz) || hz <= 1.0e-9)
    {
        throw std::runtime_error(
            "model.frequency.steer_cmd_loop_hz must be finite and > 0"
        );
    }

    return 1.0 / hz;
}

inline double getNormalizedTorqueRateUp(
    const ParamBank& P
)
{
    const double rate =
        P.get("model.drivetrain.M_dot_up");

    if (!std::isfinite(rate) || rate < 0.0)
    {
        throw std::runtime_error(
            "model.drivetrain.M_dot_up must be finite and >= 0 "
            "and is interpreted as normalized total-torque rate [1/s]"
        );
    }

    return rate;
}

inline double getNormalizedTorqueRateDown(
    const ParamBank& P
)
{
    const double rate =
        P.get("model.drivetrain.M_dot_down");

    if (!std::isfinite(rate) || rate < 0.0)
    {
        throw std::runtime_error(
            "model.drivetrain.M_dot_down must be finite and >= 0 "
            "and is interpreted as normalized total-torque rate [1/s]"
        );
    }

    return rate;
}

inline double computeTotalTorqueRateScaleMin(
    const double previous_total_Nm,
    const double target_total_Nm,
    const double max_step_up_Nm,
    const double max_step_down_Nm
)
{
    constexpr double EPS =
        1.0e-9;

    if (std::abs(target_total_Nm) <= EPS)
    {
        return 0.0;
    }

    const double allowed_low =
        previous_total_Nm - max_step_down_Nm;

    const double allowed_high =
        previous_total_Nm + max_step_up_Nm;

    const double s1 =
        allowed_low / target_total_Nm;

    const double s2 =
        allowed_high / target_total_Nm;

    return std::max(
        0.0,
        std::min(s1, s2)
    );
}

inline double computeTotalTorqueRateScaleMax(
    const double previous_total_Nm,
    const double target_total_Nm,
    const double max_step_up_Nm,
    const double max_step_down_Nm
)
{
    constexpr double EPS =
        1.0e-9;

    if (std::abs(target_total_Nm) <= EPS)
    {
        return std::numeric_limits<double>::infinity();
    }

    const double allowed_low =
        previous_total_Nm - max_step_down_Nm;

    const double allowed_high =
        previous_total_Nm + max_step_up_Nm;

    const double s1 =
        allowed_low / target_total_Nm;

    const double s2 =
        allowed_high / target_total_Nm;

    return std::max(
        0.0,
        std::max(s1, s2)
    );
}

inline double clampTotalTorqueByRateLimiterNm(
    const double target_total_Nm,
    const double previous_total_Nm,
    const double max_step_up_Nm,
    const double max_step_down_Nm
)
{
    const double allowed_low =
        previous_total_Nm - max_step_down_Nm;

    const double allowed_high =
        previous_total_Nm + max_step_up_Nm;

    return clampLocal(
        target_total_Nm,
        allowed_low,
        allowed_high
    );
}

inline double computeGlobalTorqueScaleFromWheelLimits(
    const WheelValues& torque_after_tv_Nm,
    const WheelValues& max_abs_torque_Nm
)
{
    double scale =
        1.0;

    if (std::abs(torque_after_tv_Nm.FL) > 1.0e-9)
    {
        scale =
            std::min(
                scale,
                max_abs_torque_Nm.FL
                / std::abs(torque_after_tv_Nm.FL)
            );
    }

    if (std::abs(torque_after_tv_Nm.FR) > 1.0e-9)
    {
        scale =
            std::min(
                scale,
                max_abs_torque_Nm.FR
                / std::abs(torque_after_tv_Nm.FR)
            );
    }

    if (std::abs(torque_after_tv_Nm.RL) > 1.0e-9)
    {
        scale =
            std::min(
                scale,
                max_abs_torque_Nm.RL
                / std::abs(torque_after_tv_Nm.RL)
            );
    }

    if (std::abs(torque_after_tv_Nm.RR) > 1.0e-9)
    {
        scale =
            std::min(
                scale,
                max_abs_torque_Nm.RR
                / std::abs(torque_after_tv_Nm.RR)
            );
    }

    return clampLocal(
        scale,
        0.0,
        1.0
    );
}

inline double computeScaleForOneSignedWheelTorqueLimit(
    const double torque_Nm,
    const double drive_limit_Nm,
    const double brake_limit_Nm
)
{
    constexpr double EPS =
        1.0e-9;

    if (std::abs(torque_Nm) <= EPS)
    {
        return 1.0;
    }

    const double limit_Nm =
        torque_Nm >= 0.0
            ? drive_limit_Nm
            : brake_limit_Nm;

    return
        std::max(0.0, limit_Nm)
        / std::abs(torque_Nm);
}

inline double computeGlobalScaleFromPerWheelEngineLimits(
    const WheelValues& torque_Nm,
    const double drive_limit_Nm,
    const double brake_limit_Nm
)
{
    double scale =
        1.0;

    scale =
        std::min(
            scale,
            computeScaleForOneSignedWheelTorqueLimit(
                torque_Nm.FL,
                drive_limit_Nm,
                brake_limit_Nm
            )
        );

    scale =
        std::min(
            scale,
            computeScaleForOneSignedWheelTorqueLimit(
                torque_Nm.FR,
                drive_limit_Nm,
                brake_limit_Nm
            )
        );

    scale =
        std::min(
            scale,
            computeScaleForOneSignedWheelTorqueLimit(
                torque_Nm.RL,
                drive_limit_Nm,
                brake_limit_Nm
            )
        );

    scale =
        std::min(
            scale,
            computeScaleForOneSignedWheelTorqueLimit(
                torque_Nm.RR,
                drive_limit_Nm,
                brake_limit_Nm
            )
        );

    return clampLocal(
        scale,
        0.0,
        1.0
    );
}

// ============================================================================
//                              MAIN FUNCTION
// ============================================================================

inline TorqueAllocationResult allocateWheelTorquesForDvControl(
    const ParamBank& P,
    const TorqueAllocationInput& input
)
{
    TorqueAllocationResult result;

    result.mode =
        selectTorqueAllocationMode(P);

    result.input_total_torque_cmd_Nm =
        input.total_torque_cmd_Nm;

    result.previous_total_limited_torque_Nm =
        input.previous_total_limited_torque_valid
            ? input.previous_total_limited_torque_Nm
            : 0.0;

    result.normalized_M_dot_up =
        getNormalizedTorqueRateUp(P);

    result.normalized_M_dot_down =
        getNormalizedTorqueRateDown(P);

    const double allocator_dt_s =
        getControlDtForTorqueAllocator(P);

    result.max_total_torque_step_up_Nm =
        result.normalized_M_dot_up
        * getMaxTotalWheelTorqueNm(P)
        * allocator_dt_s;

    result.max_total_torque_step_down_Nm =
        result.normalized_M_dot_down
        * getMaxTotalWheelTorqueNm(P)
        * allocator_dt_s;

    result.torque_rate_limiter_bypassed =
        input.bypass_torque_rate_limiter;

    if (result.torque_rate_limiter_bypassed)
    {
        result.rate_limited_total_torque_cmd_Nm =
            input.total_torque_cmd_Nm;
    }
    else
    {
        result.rate_limited_total_torque_cmd_Nm =
            clampTotalTorqueByRateLimiterNm(
                input.total_torque_cmd_Nm,
                result.previous_total_limited_torque_Nm,
                result.max_total_torque_step_up_Nm,
                result.max_total_torque_step_down_Nm
            );
    }

    const double total_torque_cmd_after_input_rate_limit_Nm =
        result.rate_limited_total_torque_cmd_Nm;

    const bool input_total_torque_rate_limited =
        std::abs(
            result.rate_limited_total_torque_cmd_Nm
            - input.total_torque_cmd_Nm
        ) > 1.0e-6;

    result.vx_raw_mps =
        input.vx_mps;

    result.vx_for_slip_limiter_mps =
        speedForSlipAndLimiterMps(
            input.vx_mps
        );

    result.requested_yaw_moment_Nm =
        input.desired_yaw_moment_Nm;

    result.requested_longitudinal_force_N =
        wheelTorqueToFxN(
            P,
            total_torque_cmd_after_input_rate_limit_Nm
        );

    const SteeringAngles steering_angles =
        computeAntiAckermannSteeringAngles(
            input.delta_bicycle_rad,
            P
        );

    const double delta_left_rad =
        steering_angles.delta_left_rad;

    const double delta_right_rad =
        steering_angles.delta_right_rad;

    result.delta_left_rad =
        delta_left_rad;

    result.delta_right_rad =
        delta_right_rad;

    /*
        1. Estimate normal loads.
    */

    result.Fz_N =
        estimateWheelNormalLoadsN(
            P,
            input.ax_mps2,
            input.ay_mps2,
            input.vx_mps
        );

    /*
        2. Estimate slip angles like tire model.
    */

    result.slip_angle_rad =
        estimateWheelSlipAnglesLikeTireModelRad(
            P,
            result.vx_for_slip_limiter_mps,
            input.vy_mps,
            input.yaw_rate_radps,
            delta_left_rad,
            delta_right_rad
        );

    /*
        3. Estimate lateral forces for friction pre-limiter.
    */

    result.estimated_Fy_N =
        estimateWheelLateralForcesFromSlipAnglesN(
            P,
            result.slip_angle_rad,
            result.Fz_N
        );

    /*
        4. Torque allocation.
    */

    if (result.mode == TorqueAllocationMode::JACA)
    {
        result.torque_base_Nm =
            allocateBaseTorqueJacaNm(
                P,
                total_torque_cmd_after_input_rate_limit_Nm
            );

        result.base_yaw_moment_Nm =
            computeYawMomentFromWheelTorquesNm(
                P,
                result.torque_base_Nm,
                delta_left_rad,
                delta_right_rad
            );

        result.tv_yaw_moment_target_Nm =
            input.desired_yaw_moment_Nm;

        result.delta_jaca_tv_Nm =
            computeJacaTorqueVectoringDeltaForYawMoment(
                P,
                result.tv_yaw_moment_target_Nm,
                delta_left_rad,
                delta_right_rad
            );

        result.torque_after_tv_Nm =
            applyJacaTorqueVectoringNm(
                result.torque_base_Nm,
                result.delta_jaca_tv_Nm
            );
    }
    else if (result.mode == TorqueAllocationMode::DV_AXLE)
    {
        result.torque_base_Nm =
            allocateBaseTorqueDvAxleNm(
                total_torque_cmd_after_input_rate_limit_Nm,
                result.Fz_N
            );

        result.base_yaw_moment_Nm =
            computeYawMomentFromWheelTorquesNm(
                P,
                result.torque_base_Nm,
                delta_left_rad,
                delta_right_rad
            );

        result.tv_yaw_moment_target_Nm =
            input.desired_yaw_moment_Nm;

        computeDvAxleTorqueVectoringDeltasForYawMoment(
            P,
            result.Fz_N,
            result.tv_yaw_moment_target_Nm,
            delta_left_rad,
            delta_right_rad,
            result.delta_front_tv_Nm,
            result.delta_rear_tv_Nm
        );

        result.torque_after_tv_Nm =
            applyDvAxleTorqueVectoringNm(
                result.torque_base_Nm,
                result.delta_front_tv_Nm,
                result.delta_rear_tv_Nm
            );
    }
    else
    {
        /*
            DV_QP mode.

            QP directly solves wheel forces for:
                Fx_target,
                Mz_target.

            torque_base_Nm is only debug/reference.
        */

        result.torque_base_Nm =
            allocateBaseTorqueDvAxleNm(
                total_torque_cmd_after_input_rate_limit_Nm,
                result.Fz_N
            );

        result.base_yaw_moment_Nm =
            computeYawMomentFromWheelTorquesNm(
                P,
                result.torque_base_Nm,
                delta_left_rad,
                delta_right_rad
            );

        result.tv_yaw_moment_target_Nm =
            input.desired_yaw_moment_Nm;

        const double fx_target_N =
            result.requested_longitudinal_force_N;

        WheelValues wheel_forces_N;

        result.qp_solved =
            solveDvQpWheelForcesN(
                P,
                result.Fz_N,
                fx_target_N,
                input.desired_yaw_moment_Nm,
                delta_left_rad,
                delta_right_rad,
                wheel_forces_N
            );

        if (result.qp_solved)
        {
            result.torque_after_tv_Nm =
                wheelForcesToTorquesNm(
                    P,
                    wheel_forces_N
                );

            computeEquivalentTvDeltasForDebug(
                result.torque_base_Nm,
                result.torque_after_tv_Nm,
                result.delta_front_tv_Nm,
                result.delta_rear_tv_Nm
            );
        }
        else
        {
            /*
                Fallback:
                    DV_AXLE base + DV_AXLE TV.

                Nadal bez defaultów parametrów.
            */

            result.used_fallback =
                true;

            computeDvAxleTorqueVectoringDeltasForYawMoment(
                P,
                result.Fz_N,
                result.tv_yaw_moment_target_Nm,
                delta_left_rad,
                delta_right_rad,
                result.delta_front_tv_Nm,
                result.delta_rear_tv_Nm
            );

            result.torque_after_tv_Nm =
                applyDvAxleTorqueVectoringNm(
                    result.torque_base_Nm,
                    result.delta_front_tv_Nm,
                    result.delta_rear_tv_Nm
                );
        }
    }

    result.achieved_yaw_moment_before_limit_Nm =
        computeYawMomentFromWheelTorquesNm(
            P,
            result.torque_after_tv_Nm,
            delta_left_rad,
            delta_right_rad
        );

    result.achieved_longitudinal_force_before_limit_N =
        computeLongitudinalBodyForceFromWheelTorquesN(
            P,
            result.torque_after_tv_Nm,
            delta_left_rad,
            delta_right_rad
        );

    result.yaw_moment_error_before_limit_Nm =
        result.tv_yaw_moment_target_Nm
        - result.achieved_yaw_moment_before_limit_Nm;

    result.longitudinal_force_error_before_limit_N =
        result.requested_longitudinal_force_N
        - result.achieved_longitudinal_force_before_limit_N;

    result.total_torque_after_tv_Nm =
        sumWheelValues(
            result.torque_after_tv_Nm
        );

    /*
        5. Global scale limiter after final torque_after_tv.
    */

    const bool use_friction_ellipse =
        paramFlag(
            P,
            "general.use_friction_elipse_limiter"
        );

    const WheelValues mechanical_limit =
        getMaxAbsWheelTorqueMechanicalNm(P);

    constexpr double FRICTION_ELLIPSE_MIN_SPEED_MPS =
        3.0;

    const bool friction_ellipse_speed_active =
        std::abs(input.vx_mps) > FRICTION_ELLIPSE_MIN_SPEED_MPS;

    /*
        Mechanical torque limits are always active.

        Friction ellipse is active only above 3 m/s real vehicle speed.
        Below that, slip/Fy estimation is too noisy and too artificial because
        vx_for_slip_limiter_mps is deliberately floored to 2 m/s only to avoid
        singular slip-angle calculation at standstill.
    */
    if (use_friction_ellipse && friction_ellipse_speed_active)
    {
        result.max_abs_torque_from_friction_Nm =
            computeMaxAbsWheelTorqueFromFrictionEllipseNm(
                P,
                result.Fz_N,
                result.estimated_Fy_N
            );

        result.max_abs_torque_after_all_limits_Nm =
            minWheelValues(
                mechanical_limit,
                result.max_abs_torque_from_friction_Nm
            );
    }
    else
    {
        result.max_abs_torque_from_friction_Nm =
            mechanical_limit;

        result.max_abs_torque_after_all_limits_Nm =
            mechanical_limit;
    }

    result.hard_limit_scale =
        computeGlobalTorqueScaleFromWheelLimits(
            result.torque_after_tv_Nm,
            result.max_abs_torque_after_all_limits_Nm
        );

    if (result.torque_rate_limiter_bypassed)
    {
        result.total_torque_rate_scale_min =
            0.0;

        result.total_torque_rate_scale_max =
            std::numeric_limits<double>::infinity();

        result.total_torque_rate_limited_scale =
            1.0;

        result.torque_rate_limited =
            false;

        result.torque_rate_forced_over_hard_limit =
            false;

        result.global_scale =
            result.hard_limit_scale;
    }
    else
    {
        result.total_torque_rate_scale_min =
            computeTotalTorqueRateScaleMin(
                result.previous_total_limited_torque_Nm,
                result.total_torque_after_tv_Nm,
                result.max_total_torque_step_up_Nm,
                result.max_total_torque_step_down_Nm
            );

        result.total_torque_rate_scale_max =
            computeTotalTorqueRateScaleMax(
                result.previous_total_limited_torque_Nm,
                result.total_torque_after_tv_Nm,
                result.max_total_torque_step_up_Nm,
                result.max_total_torque_step_down_Nm
            );

        result.total_torque_rate_limited_scale =
            clampLocal(
                1.0,
                result.total_torque_rate_scale_min,
                result.total_torque_rate_scale_max
            );

        result.global_scale =
            clampLocal(
                result.hard_limit_scale,
                result.total_torque_rate_scale_min,
                result.total_torque_rate_scale_max
            );

        result.torque_rate_forced_over_hard_limit =
            result.global_scale > result.hard_limit_scale + 1.0e-9;

        result.torque_rate_limited =
            input_total_torque_rate_limited
            || std::abs(
                result.total_torque_rate_limited_scale - 1.0
            ) > 1.0e-6
            || result.torque_rate_forced_over_hard_limit;
    }

    result.limited =
        std::abs(result.global_scale - 1.0) > 1.0e-6;

    result.torque_limited_Nm =
        scaleWheelValues(
            result.torque_after_tv_Nm,
            result.global_scale
        );

    /*
        6. Final per-wheel engine-side torque limiter.

        This is intentionally applied after all other limiters.

        It checks the final wheel torques against engine-side per-wheel limits
        converted to wheel side:

            drive wheel limit = wheel_max_torque_engine_drive_Nm * gear_ratio
            brake wheel limit = wheel_max_torque_engine_brake_Nm * gear_ratio

        One global scale is applied to all four wheels, so base allocation and
        TV balance are preserved.
    */

    result.wheel_drive_limit_from_engine_Nm =
        getWheelDriveLimitFromEngineNm(P);

    result.wheel_brake_limit_from_engine_Nm =
        getWheelBrakeLimitFromEngineNm(P);

    result.final_engine_per_wheel_limit_scale =
        computeGlobalScaleFromPerWheelEngineLimits(
            result.torque_limited_Nm,
            result.wheel_drive_limit_from_engine_Nm,
            result.wheel_brake_limit_from_engine_Nm
        );

    result.final_engine_per_wheel_limited =
        std::abs(
            result.final_engine_per_wheel_limit_scale
            - 1.0
        ) > 1.0e-6;

    if (result.final_engine_per_wheel_limited)
    {
        result.torque_limited_Nm =
            scaleWheelValues(
                result.torque_limited_Nm,
                result.final_engine_per_wheel_limit_scale
            );

        result.global_scale *=
            result.final_engine_per_wheel_limit_scale;
    }

    result.limited =
        result.limited
        || result.final_engine_per_wheel_limited;

    result.achieved_yaw_moment_after_limit_Nm =
        computeYawMomentFromWheelTorquesNm(
            P,
            result.torque_limited_Nm,
            delta_left_rad,
            delta_right_rad
        );

    result.achieved_longitudinal_force_after_limit_N =
        computeLongitudinalBodyForceFromWheelTorquesN(
            P,
            result.torque_limited_Nm,
            delta_left_rad,
            delta_right_rad
        );

    result.yaw_moment_error_after_limit_Nm =
        result.tv_yaw_moment_target_Nm
        - result.achieved_yaw_moment_after_limit_Nm;

    result.longitudinal_force_error_after_limit_N =
        result.requested_longitudinal_force_N
        - result.achieved_longitudinal_force_after_limit_N;

    result.total_torque_limited_Nm =
        sumWheelValues(
            result.torque_limited_Nm
        );

    return result;
}

} // namespace skidpad_control
