std_msgs/Header header

int32 if_safe

float64 v_curr_mps
float64 v_ref_mps
float64 v_error_mps

float64 omega_curr_radps
float64 omega_ref_radps
float64 omega_error_radps

float64 curr_slip_ratio
float64 ref_slip_ratio
float64 slip_ratio_error

float64 toruque_cmd_Nm
float64 throttle_cmd_percent

float64 distance_left_to_end
float64 distance_optimistic_left_to_brake

float64 s_ref_m
float64 s_curr_m

string phase

string safety_reason
int32 emergency_brake_requested

float64 max_speed_global_mps
float64 target_slip_ratio

float32 curr_ax_mps2
float32 ref_ax_mps2
float32 ax_error_mps2
